# Generated by Django 6.0 on 2025-12-29 03:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(help_text='Número único de orden (auto-generado)', max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente si no está registrado', max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('order_type', models.CharField(choices=[('in_store', 'Venta en Tienda'), ('online', 'Venta Online'), ('phone', 'Venta por Teléfono'), ('delivery', 'Entrega a Domicilio')], default='in_store', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('processing', 'En Proceso'), ('ready', 'Lista para Entregar'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal antes de descuentos e impuestos', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total de descuentos', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de impuestos', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de envío', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total final a pagar', max_digits=12)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la orden')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre la orden')),
                ('customer_notes', models.TextField(blank=True, help_text='Notas del cliente (instrucciones especiales)')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Empleado asignado para procesar la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Bodega desde donde se despacha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Cantidad ordenada', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la venta', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento aplicado', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de descuento en dinero', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de impuesto aplicada', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de impuesto', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal del item (precio × cantidad)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total del item después de descuentos e impuestos', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.productvariant')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'db_table': 'order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, help_text='ID de transacción externa (Stripe, PayPal, etc)', max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('online', 'Pago Online'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Fecha del pago')),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'order_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('customer_request', 'Solicitud del Cliente'), ('defective', 'Producto Defectuoso'), ('wrong_item', 'Item Incorrecto'), ('not_satisfied', 'Cliente Insatisfecho'), ('other', 'Otro')], max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'db_table': 'order_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='orders_busines_54613c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'order_date'], name='orders_custome_9fba8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_order_d_6e39a9_idx'),
        ),
    ]
