# Generated by Django 6.0 on 2025-12-30 16:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_number', models.CharField(help_text='Número único de reserva (auto-generado)', max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(help_text='Fecha y hora de finalización')),
                ('duration_minutes', models.IntegerField(help_text='Duración en minutos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False, help_text='¿Se envió recordatorio?')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total de la reserva', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notas internas')),
                ('customer_notes', models.TextField(blank=True, help_text='Notas del cliente (solicitudes especiales)')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.customer')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio del servicio al momento de la reserva', max_digits=10)),
                ('duration_minutes', models.IntegerField(help_text='Duración estimada del servicio')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(help_text='Servicio (Product donde is_service=True)', on_delete=django.db.models.deletion.PROTECT, related_name='reservation_services', to='core.product')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Servicio de Reserva',
                'verbose_name_plural': 'Servicios de Reserva',
                'db_table': 'reservation_services',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Reserva',
                'verbose_name_plural': 'Historial de Estados de Reservas',
                'db_table': 'reservation_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Título profesional (ej: Barbero Senior, Estilista)', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Biografía o descripción del proveedor')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo para recibir reservas?')),
                ('accepts_walk_ins', models.BooleanField(default=True, help_text='¿Acepta clientes sin cita?')),
                ('working_hours', models.JSONField(default=dict, help_text='Horario de trabajo por día')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor de Servicio',
                'verbose_name_plural': 'Proveedores de Servicios',
                'db_table': 'service_providers',
                'ordering': ['user__first_name'],
                'unique_together': {('business', 'user')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Empleado que realizará el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.serviceprovider'),
        ),
        migrations.CreateModel(
            name='ServiceProviderAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('availability_type', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'No Disponible'), ('blocked', 'Bloqueado')], max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Razón de la excepción (ej: Vacaciones, Evento especial)', max_length=200)),
                ('is_recurring', models.BooleanField(default=False, help_text='¿Esta excepción se repite?')),
                ('recurring_pattern', models.JSONField(blank=True, default=dict, help_text='Patrón de repetición (semanal, mensual, etc.)')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='reservations.serviceprovider')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Proveedor',
                'verbose_name_plural': 'Disponibilidad de Proveedores',
                'db_table': 'service_provider_availability',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField(blank=True, help_text='Fecha preferida (opcional)', null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Hora preferida (opcional)', null=True)),
                ('status', models.CharField(choices=[('waiting', 'En Espera'), ('notified', 'Notificado'), ('scheduled', 'Agendado'), ('cancelled', 'Cancelado')], default='waiting', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to='core.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to='core.customer')),
                ('desired_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_lists', to='reservations.serviceprovider')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'db_table': 'waiting_lists',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['business', 'status'], name='reservation_busines_81ad39_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['service_provider', 'start_datetime'], name='reservation_service_230d67_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', 'start_datetime'], name='reservation_custome_164195_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='reservation_start_d_53785c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovideravailability',
            index=models.Index(fields=['service_provider', 'start_datetime', 'end_datetime'], name='service_pro_service_bd3620_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['business', 'status'], name='waiting_lis_busines_185cca_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['service_provider', 'status'], name='waiting_lis_service_a4ae4f_idx'),
        ),
    ]
