# Generated by Django 6.0 on 2025-12-30 17:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Código de cuenta (ej: 1001, 4001)', max_length=20)),
                ('name', models.CharField(help_text='Nombre de la cuenta (ej: Caja, Ventas)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('asset', 'Activo'), ('liability', 'Pasivo'), ('equity', 'Capital'), ('revenue', 'Ingreso'), ('expense', 'Gasto')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance actual de la cuenta', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.business')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='finance.account')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'accounts',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expense_number', models.CharField(help_text='Número único de gasto (auto-generado)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('rent', 'Arriendo'), ('utilities', 'Servicios Públicos'), ('salaries', 'Salarios'), ('supplies', 'Suministros'), ('marketing', 'Marketing'), ('maintenance', 'Mantenimiento'), ('insurance', 'Seguros'), ('taxes', 'Impuestos'), ('equipment', 'Equipo'), ('other', 'Otro')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Nombre del proveedor', max_length=200)),
                ('expense_date', models.DateField(help_text='Fecha del gasto')),
                ('due_date', models.DateField(blank=True, help_text='Fecha de vencimiento de pago', null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partially_paid', 'Parcialmente Pagado'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Método de pago utilizado', max_length=50)),
                ('receipt_url', models.URLField(blank=True, help_text='URL del recibo/factura en S3')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(help_text='Número único de factura (auto-generado)', max_length=50, unique=True)),
                ('issue_date', models.DateField(help_text='Fecha de emisión')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('partially_paid', 'Parcialmente Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Términos y condiciones')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='orders.order')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del término (ej: Net 30, 50% Adelanto)', max_length=100)),
                ('days', models.IntegerField(help_text='Días de plazo para pago')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento por pronto pago', max_digits=5)),
                ('discount_days', models.IntegerField(default=0, help_text='Días para aplicar descuento')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='core.business')),
            ],
            options={
                'verbose_name': 'Término de Pago',
                'verbose_name_plural': 'Términos de Pago',
                'db_table': 'payment_terms',
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_number', models.CharField(help_text='Número único de transacción (auto-generado)', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra'), ('payment', 'Pago'), ('receipt', 'Cobro'), ('transfer', 'Transferencia'), ('adjustment', 'Ajuste'), ('refund', 'Reembolso'), ('expense', 'Gasto'), ('other', 'Otro')], max_length=20)),
                ('transaction_date', models.DateTimeField(help_text='Fecha de la transacción')),
                ('reference_type', models.CharField(blank=True, help_text='Tipo de documento (Order, Invoice, etc)', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='ID del documento relacionado', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False, help_text='¿La transacción está contabilizada?')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'transaction_entries',
                'ordering': ['transaction', 'entry_type'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'account_type'], name='accounts_busines_aba7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'is_active'], name='accounts_busines_449dca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('business', 'code')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'category'], name='expenses_busines_e69c54_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'payment_status'], name='expenses_busines_dfb1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'status'], name='invoices_busines_2564df_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='invoices_custome_90a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', 'transaction_type'], name='transaction_busines_fef2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='transaction_referen_c8c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['transaction', 'account'], name='transaction_transac_1d27af_idx'),
        ),
    ]
