# Generated by Django 6.0 on 2026-01-02 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('cashier', 'Cajero')], db_index=True, default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('business_owner', 'Propietario de negocio'), ('employee', 'Empleado'), ('customer', 'Cliente'), ('admin', 'Administrador')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['business', 'is_active', 'role'], name='business_me_busines_c07267_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customers_custome_41ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'email_verified'], name='users_is_acti_ecda13_idx'),
        ),
    ]
