# Generated by Django 6.0 on 2025-12-30 21:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(help_text='Número único de transferencia (auto-generado)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En Proceso de Transferencia'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('transfer_date', models.DateTimeField(help_text='Fecha de inicio de la transferencia')),
                ('expected_arrival', models.DateTimeField(blank=True, help_text='Fecha esperada de llegada', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='Fecha de completación', null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='core.business')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Stock',
                'verbose_name_plural': 'Transferencias de Stock',
                'db_table': 'stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_sent', models.IntegerField(help_text='Cantidad enviada', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.IntegerField(default=0, help_text='Cantidad recibida (puede diferir de la enviada)')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre discrepancias, daños, etc.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant')),
            ],
            options={
                'verbose_name': 'Item de Transferencia',
                'verbose_name_plural': 'Items de Transferencia',
                'db_table': 'stock_transfer_items',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nombre de la bodega (ej: Bodega Principal, Tienda Centro)', max_length=100)),
                ('code', models.CharField(help_text='Código único de la bodega (ej: BOD-01, TDA-CENTRO)', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_main', models.BooleanField(default=False, help_text='¿Es la bodega principal?')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.business')),
                ('manager', models.ForeignKey(blank=True, help_text='Encargado de la bodega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'warehouses',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Cantidad disponible en esta bodega')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Cantidad reservada (en órdenes pendientes)')),
                ('location', models.CharField(blank=True, help_text='Ubicación física dentro de la bodega (ej: Pasillo 3, Estante A)', max_length=100)),
                ('min_stock_level', models.IntegerField(default=0, help_text='Nivel mínimo antes de alertar')),
                ('max_stock_level', models.IntegerField(default=0, help_text='Nivel máximo recomendado')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo promedio ponderado', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Si el producto tiene variantes, especificar cuál', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'db_table': 'inventory_items',
                'ordering': ['warehouse', 'product'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('transfer', 'Transferencia'), ('adjustment', 'Ajuste'), ('return', 'Devolución'), ('damage', 'Daño/Pérdida'), ('production', 'Producción'), ('consumption', 'Consumo')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Cantidad movida (positivo = entrada, negativo = salida)')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, help_text='Tipo de documento (Order, PurchaseOrder, Transfer, etc)', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='ID del documento relacionado', max_length=100)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario en este movimiento', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del movimiento', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.business')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'movement_type'], name='inventory_m_busines_d56ff9_idx'), models.Index(fields=['inventory_item', 'created_at'], name='inventory_m_invento_9275a5_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_m_referen_ce9f4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('count_discrepancy', 'Discrepancia en Conteo'), ('damage', 'Producto Dañado'), ('theft', 'Robo'), ('expired', 'Vencido'), ('found', 'Producto Encontrado'), ('correction', 'Corrección de Error'), ('other', 'Otro')], max_length=30)),
                ('previous_quantity', models.IntegerField()),
                ('adjustment_quantity', models.IntegerField(help_text='Cantidad ajustada (positivo = aumenta, negativo = disminuye)')),
                ('new_quantity', models.IntegerField()),
                ('notes', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.business')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Stock',
                'verbose_name_plural': 'Ajustes de Stock',
                'db_table': 'stock_adjustments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'reason'], name='stock_adjus_busines_28a339_idx'), models.Index(fields=['inventory_item', 'created_at'], name='stock_adjus_invento_9072c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['business', 'is_active'], name='warehouses_busines_647f04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('business', 'code')},
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['business', 'status'], name='stock_trans_busines_8a23fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='stock_trans_from_wa_47df74_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['warehouse', 'product'], name='inventory_i_warehou_daba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['quantity'], name='inventory_i_quantit_2c9a94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('warehouse', 'product', 'variant')},
        ),
    ]
