# Generated by Django 6.0 on 2025-12-30 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('system', 'Sistema'), ('order', 'Orden'), ('reservation', 'Reserva'), ('inventory', 'Inventario'), ('finance', 'Finanzas')], default='system', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10)),
                ('url', models.URLField(blank=True, help_text='URL de destino en el frontend')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(help_text='Negocio al que pertenece la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.business')),
                ('recipient', models.ForeignKey(help_text='Usuario destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'recipient', 'is_read'], name='notificatio_busines_c0643c_idx'), models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_1897f3_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_22e6c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_in_app', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=False)),
                ('allow_sms', models.BooleanField(default=False)),
                ('allow_push', models.BooleanField(default=False)),
                ('muted_types', models.JSONField(blank=True, default=list, help_text='Lista de tipos silenciados (ej: ["inventory", "finance"])')),
                ('is_muted', models.BooleanField(default=False, help_text='Silenciar todas las notificaciones para este negocio')),
                ('quiet_hours', models.JSONField(blank=True, default=dict, help_text='Horario de silencio (ej: {"start": "22:00", "end": "07:00"})')),
                ('business', models.ForeignKey(help_text='Negocio para el que aplican las preferencias', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'notification_preferences',
                'indexes': [models.Index(fields=['user', 'business'], name='notificatio_user_id_8ff02d_idx')],
                'unique_together': {('user', 'business')},
            },
        ),
    ]
